name: Deploy API Image to GHCR

on:
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Download dataset'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Manuel-Materazzo/build-files'
          version: 'tags/problematic-internet-usage'
          regex: true
          file: ".*\\.csv"
          target: 'resources/cmi-problematic-internet-usage/'
          token: ${{secrets.ACTIONS_PAT}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/manuel-materazzo/problematic-internet-use:latest
          docker push ghcr.io/manuel-materazzo/problematic-internet-use:latest
